# -*- coding: utf-8 -*-
"""Bug_Report_Tabassum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ruQrJ7Spqg61e6w6bO1Jast1ZJdkSSbt
"""

import pandas as pd

def main():
    try:
        # Load the existing Excel file
        excel_file = "Bug_Report_Tabassum.xlsx"
        df = pd.read_excel(excel_file)

        # Display basic info in console
        print("✅ Bug report loaded successfully!")
        print(f"Total bugs found: {len(df)}\n")
        print("Bug IDs and Titles:")
        for idx, row in df.iterrows():
            print(f"{row['Bug ID']}: {row['Title']}")

        # Optional: export again (demonstrates automation)
        output_file = "Bug_Report_Tabassum_output.xlsx"
        df.to_excel(output_file, index=False)
        print(f"\n✅ Bug report exported successfully to {output_file}")

    except Exception as e:
        print(f"❌ Error: {e}")

if __name__ == "__main__":
    main()